version: "3.9"

services:
  #mongodb service
  mongo_db:
    container_name: db_booking
    image: mongo:latest
    restart: always
    volumes:
      - mongo_data:/data/db
  #node api service
  api:
    build: .
    ports:
      #local -> docker
      - 1111:3000
      - 2222:3000
      - 3333:3000
      - 4444:3000
      - 5555:3000

    environment:
      PORT: 3000
      DEV_MODE: development
      MONGO: mongodb://mongo_db:27017/booking
      JWT_SECRET: W9bfhau7WucAtBICJ058UrsRwJzqeR7btqs9+ExnjcQ=
    depends_on:
      - mongo_db

volumes:
  mongo_data: {}
